# Generated by Django 4.0.6 on 2022-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('gender', models.CharField(max_length=50, verbose_name='Género')),
                ('nacionality', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('profession', models.CharField(max_length=50, verbose_name='Profesión')),
                ('status', models.CharField(max_length=50, verbose_name='Estado Civil')),
                ('childs', models.CharField(max_length=50, verbose_name='Cantidad Hijos')),
                ('sport', models.CharField(max_length=50, verbose_name='Deporte Preferido')),
                ('music', models.CharField(max_length=50, verbose_name='Tipo de Música')),
                ('food', models.CharField(max_length=50, verbose_name='Tipo de Comida')),
                ('drink', models.CharField(max_length=50, verbose_name='Tipo de Bebida')),
                ('contact_type', models.IntegerField(choices=[[0, 'Presencial'], [1, 'On Line']], verbose_name='Tipo de Contacto')),
                ('subscription', models.BooleanField(default=False, verbose_name='Suscribirme a Correos Informativos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
        ),
    ]
