# Generated by Django 4.0.6 on 2022-12-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_type',
            field=models.IntegerField(choices=[[0, 'Presencial'], [1, 'On Line']], default=0, verbose_name='Tipo de Contacto'),
        ),
    ]
