# Generated by Django 4.0.6 on 2022-12-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_profile_options_profile_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_type',
            field=models.CharField(choices=[('Presencial', 'presencial'), ('On-line', 'on-line')], default='Presencial', max_length=10, verbose_name='Tipo de Contacto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Mensaje'),
        ),
    ]
